- name: Install gstreamer (good, bad, ugly)
  apt:
    update_cahce: true
    name: 
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - gstreamer1.0-plugins-*
      - gstreamer1.0-tools
      - gstreamer1.0-vaapi
      - gstreamer1.0-x