---
# tasks file for ansible-role-print-nanny
- include_role:
    name: bitsy.janus_gateway
  tags:
    - janus_gateway
    - print_nanny
    
- import_tasks: gstreamer.yml
  tags:
    - gstreamer
    - print_nanny