---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian12
    image: debian:buster
    pre_build_image: true
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - destroy
